/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.papacharlie.gorestli;

import io.papacharlie.gorestli.json.GoRestliSpec;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.testng.annotations.Test;


public class GoRestliRestSpecParserTest {
  private static Path TEST_SUITE_ROOT =
      Paths.get(System.getProperty("user.dir"), "../internal/tests/rest.li-test-suite/client-testsuite")
          .toAbsolutePath()
          .normalize();

  /**
   * Simple sanity check. The end-to-end testing happens in the root Makefile
   */
  @Test
  public void test() {
    GoRestliSpec snapshot = new GoRestliRestSpecParser(
        TEST_SUITE_ROOT.resolve("schemas").toString(),
        TEST_SUITE_ROOT.resolve("restspecs").toString()).parse();
    System.out.println(Utils.toJson(snapshot));
  }
}
