package main

import (
	"os"
	"os/exec"
)

func main() {
	cmd := exec.Command("go", "list", "-f", "\t"+`"{{ .ImportPath }}": "{{ .Name }}",`, "all")
	cmd.Stderr = os.Stderr

	imports, err := cmd.Output()
	if err != nil {
		panic(err)
	}

	const out = "codefile_imports.gr.go"
	_ = os.Remove(out)
	err = os.WriteFile(out, []byte(
		`// Code generated by "github.com/PapaCharlie/go-restli/internal/importnames"; DO NOT EDIT.

package utils

var jenImportNames = map[string]string{
`+string(imports)+`
}
`), os.FileMode(0444))
	if err != nil {
		panic(err)
	}

}
