package main

import (
	"io/ioutil"
	"os"
	"os/exec"

	"github.com/PapaCharlie/go-restli/codegen/utils"
)

func main() {
	cmd := exec.Command("go", "list", "-f", "\t"+`"{{ .ImportPath }}": "{{ .Name }}",`, "all")
	cmd.Stderr = os.Stderr

	imports, err := cmd.Output()
	if err != nil {
		panic(err)
	}

	err = ioutil.WriteFile("codefile_imports.go", []byte(
		`// Code generated by "github.com/PapaCharlie/go-restli/internal/importnames"; DO NOT EDIT.

package utils

var jenImportNames = map[string]string{
`+string(imports)+`
}
`), utils.ReadOnlyPermissions)
	if err != nil {
		panic(err)
	}

}
